# Generated by Django 5.2.16 on 2026-07-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/Razón Social')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('redes_sociales', models.CharField(blank=True, help_text='Ej: Facebook, Instagram', max_length=100, null=True)),
                ('es_recurrente', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Ej: Gigantografía 3x2m, Tarjetas personales')),
                ('especificaciones', models.TextField(blank=True, help_text='Detalles técnicos: Tipo de lona, ojales, etc.', null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de adelanto'), ('Diseno', 'En diseño'), ('Correccion', 'En corrección'), ('Validado', 'Validado para producción'), ('Produccion', 'En producción (Plotter/Impresión)'), ('Entregado', 'Entregado al cliente')], default='Pendiente', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_adelanto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Yape', 'Yape'), ('Plin', 'Plin'), ('Transferencia', 'Transferencia Bancaria')], default='Efectivo', max_length=20)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='gestion.ordentrabajo')),
            ],
        ),
    ]
