# Generated by Django 5.2.16 on 2026-07-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_ingreso']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(choices=[('cliente', 'Cliente'), ('staff', 'Staff')], default='cliente', max_length=20)),
                ('mensaje', models.TextField()),
                ('canal', models.CharField(default='whatsapp', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='gestion.cliente')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='gestion.ordentrabajo')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
