# Generated by Django 5.2.16 on 2026-07-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_cliente_options_alter_ordentrabajo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Grafimaster', max_length=150, verbose_name='Nombre de la empresa')),
                ('descripcion_sistema', models.TextField(default='Sistema de gestión moderno para clientes, órdenes y conversaciones.', verbose_name='Descripción del sistema')),
                ('slogan', models.CharField(blank=True, default='Gestión profesional para tu empresa.', max_length=200, verbose_name='Slogan')),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
                'verbose_name_plural': 'Configuración de empresa',
            },
        ),
    ]
